site_name: python 101 course
theme:
  features:
    - navigation.tabs
  feature:
    tabs: true
  favicon: 'assets/img/favicon.ico'
  name: 'material'
  language: 'ru'
  palette:
    primary: 'black'
    accent: 'indigo'
copyright: 'copyleft &copy; copyright'

nav:
  - Первая неделя:
    - Линукс и Баш: week1/bash.md
    - Гит и Гитхаб: week1/git.md
  - Вторая неделя:
    - GitHub Flow и ветки: week2/github.md
    - Bash-скриптинг: week2/bash-scripting.md
  - Третья неделя:
    - Настройка окружения: week3/vscode.md
    - Основы Python: week3/python_intro.md
    - Ветвления и итерации: week3/if_for.md
  - Четвертая неделя:
    - Интерфейсы и API: week4/api.md
  - Что здесь происходит?: wtf.md
  - Что значит «сделать»: done.md

extra:
  search:
    language: 'en, ru'

markdown_extensions:
  - codehilite
